baseURL = 'https://www.letmecompile.com/'
languageCode = 'ko-kr'
defaultContentLanguage = 'ko-kr'
title = 'Knowledge Logger'
theme = 'PaperMod'
enableRobotsTXT = true

# Korean language configuration
[languages]
  [languages.ko-kr]
    languageName = "한국어"
    weight = 1
    title = "Knowledge Logger"

# URL structure to match WordPress permalinks
[permalinks]
  posts = "/:slug/"

# Taxonomy permalinks to match WordPress
[taxonomies]
  category = "categories"
  tag = "tags"

# Configure taxonomy permalinks
[params.taxonomies]
  category = "/category/:slug/"
  tag = "/tag/:slug/"

# Enable sitemap generation
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Output formats for search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

# URL handling for WordPress compatibility
[params.urls]
  category = "/category"
  tag = "/tag"

# Language-specific taxonomy configuration for templates
# tags section in single.html does not show up without this
[languages.ko-kr.params.taxonomies]
  tag = "tags"
  category = "categories"

[params]
  # Enable only for testing locally
  # env = "production"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  # Enable syntax highlighting
  assets.disableHLJS = false
  
  # Favicon configuration
  assets.favicon = "/images/profile_bg_white.png"
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/youngjae-kwon-a73a147/"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/yjiq150"

  # Search configuration with Fuse.js
  [params.fuseOpts]
    isCaseSensitive = false
    includeScore = false
    includeMatches = false
    minMatchCharLength = 2
    shouldSort = true
    threshold = 0.4
    distance = 100
    ignoreLocation = true
    keys = ["title", "permalink", "summary", "content"]

  [params.profileMode]
    enabled = true
    title = "Knowledge Logger"
    subtitle = "A blog about programming, development, and technology"
     imageUrl = "images/profile_bg_white.png"  # Add your profile image path here
     imageWidth = 150
     imageHeight = 150

  # Commented out homeInfoParams as it conflicts with profileMode
  # [params.homeInfoParams]
  #   Title = "Welcome to Knowledge Logger"
  #   Content = "A blog about programming, development, and technology"

  # SEO Settings similar to All In One SEO Pack
  [params.seo]
    # Enable Open Graph
    enableOpenGraph = true
    # Enable Twitter Cards
    enableTwitterCards = true
    # Enable JSON-LD structured data
    enableJSONLD = true
    # Default meta description for pages without one
    defaultDescription = "Programming insights, development experiences, and technical knowledge from Knowledge Logger"
    # Site verification codes (add when available)
    googleSiteVerification = ""
    bingSiteVerification = ""

# Markdown configuration to allow raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    guessSyntax = true
    hl_Lines = ""
    hl_inline = false
    anchorLineNos = false
    codeFences = true
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 30
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 40
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 50

[services]
  [services.disqus]
    shortname = 'yjiq150'
